name: at_robot

on: 
  pull_request_review_comment:
    types: [created, edited]
  issue_comment:
    types: [created, edited]

jobs:
  at_robot:
    if: |
      contains(github.event.comment.body, '@cocos-wahah run build')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run test build
        run: |
          echo "call run test build"
          submit_branch=`echo ${{ github.event.comment.body }} | grep submit | awk '{print $NF}'`
          echo "提交到仓库(cocos-engine-external), 分支: ${submit_branch}"
