name: at_robot

on: 
  pull_request_review_comment:
    types: [created, edited]
  issue_comment:
    types: [created, edited]

jobs:
  at_robot:
    if: |
      contains(github.event.comment.body, '@cocos-robot run test cases')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run test cases
        run: |
          echo "call run test cases"
