name: needs

on: [push]

jobs:
  win_build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  mac_build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
  over_build:
    runs-on: ubuntu-latest
    needs: [win_build, mac_build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
