name: Schedule

on:
  schedule:
    - cron: '*/5 * * * *'
    # minute (0 - 59) hour (0 - 23) day of the month (1 - 31) month (1 - 12 or JAN-DEC) day of the week (0 - 6 or SUN-SAT)

jobs:
  Schedule:
    strategy:
      matrix:
        branch: ['v3.5.0', 'v3.6.0']

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
